# 默认学期
default:
  message: LNTUHelper iOS App 公测开始啦，小伙伴们欢呼雀跃吧
  semester_start_date: 2020-08-31
  semester: 2020-秋

# sentry-sdk-key
sentry:
  url: https://"*********"@o396131.ingest.sentry.io/5249091

# 线上、测试数据库
mysql:
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  db_name: hilntu # 线上数据库名
  test_db_name: test_hilntu # 测试数据库名

# 教务有效测试账号
education-account:
  username: 1710030215
  password: test

# 素拓有效测试账号
quality-account:
  username: 1710030215
  password: test
