mysql:
  #  线上数据库
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  name: hilntu #数据库名

test-mysql:
  #  测试数据库
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  name: test_hilntu #测试数据库名

test-account:
  # 测试账号
  - 1710030111: passwordss
  - 1710030112: passwordsss
